# Generated by Django 3.1.7 on 2021-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallPlayer',
            fields=[
                ('player_id', models.CharField(db_column='player_id', max_length=255, primary_key=True, serialize=False)),
                ('birth_country', models.CharField(blank=True, db_column='birth_country', max_length=255, null=True)),
                ('birth_state', models.CharField(blank=True, db_column='birth_state', max_length=255, null=True)),
                ('birth_city', models.CharField(blank=True, db_column='birth_city', max_length=255, null=True)),
                ('name_first', models.CharField(blank=True, db_column='name_first', max_length=255, null=True)),
                ('name_last', models.CharField(blank=True, db_column='name_last', max_length=255, null=True)),
                ('player_number', models.IntegerField(null=True)),
                ('player_pos', models.CharField(default='Player Position', max_length=80, null=True)),
                ('weight', models.IntegerField(blank=True, db_column='weight', null=True)),
                ('height', models.IntegerField(blank=True, db_column='height', null=True)),
                ('bats', models.CharField(blank=True, db_column='bats', max_length=255, null=True)),
                ('throws', models.CharField(blank=True, db_column='throws', max_length=255, null=True)),
            ],
            options={
                'db_table': 'BallPlayer',
            },
        ),
    ]
