# Generated by Django 3.1.7 on 2021-03-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, db_column='player_id', max_length=9, null=True)),
                ('year_id', models.SmallIntegerField(blank=True, db_column='year_id', null=True)),
                ('stint', models.SmallIntegerField(blank=True, db_column='stint', null=True)),
                ('team_id', models.CharField(blank=True, db_column='team_id', max_length=3, null=True)),
                ('league_id', models.CharField(blank=True, db_column='league_id', max_length=2, null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('at_bats', models.IntegerField(blank=True, db_column='at_bats', null=True)),
                ('runs', models.IntegerField(blank=True, db_column='runs', null=True)),
                ('hits', models.IntegerField(blank=True, db_column='hits', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('cs', models.IntegerField(blank=True, db_column='CS', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('ibb', models.IntegerField(blank=True, db_column='IBB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('sh', models.IntegerField(blank=True, db_column='SH', null=True)),
                ('sf', models.IntegerField(blank=True, db_column='SF', null=True)),
                ('gidp', models.IntegerField(blank=True, db_column='GIDP', null=True)),
            ],
            options={
                'db_table': 'Batting',
            },
        ),
    ]
