# Generated by Django 3.1.7 on 2021-03-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0002_batting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, db_column='player_id', max_length=9, null=True)),
                ('year_id', models.IntegerField(blank=True, db_column='year_id', null=True)),
                ('stint', models.IntegerField(blank=True, db_column='stint', null=True)),
                ('team_id', models.CharField(blank=True, db_column='team_id', max_length=3, null=True)),
                ('league_id', models.CharField(blank=True, db_column='league_id', max_length=2, null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('gs', models.IntegerField(blank=True, db_column='GS', null=True)),
                ('shutouts', models.IntegerField(blank=True, db_column='shutouts', null=True)),
                ('saves', models.IntegerField(blank=True, db_column='saves', null=True)),
                ('outs_pitched', models.IntegerField(blank=True, db_column='outs_pitched', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('strikeouts', models.IntegerField(blank=True, db_column='strikeouts', null=True)),
                ('baopp', models.FloatField(blank=True, db_column='BAOpp', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
                ('ibb', models.IntegerField(blank=True, db_column='IBB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('bk', models.IntegerField(blank=True, db_column='BK', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
            ],
            options={
                'db_table': 'Pitching',
            },
        ),
    ]
