# Generated by Django 3.1.7 on 2021-03-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0003_pitching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('year_id', models.IntegerField(db_column='year_id', primary_key=True, serialize=False)),
                ('league_id', models.CharField(blank=True, db_column='league_id', max_length=2, null=True)),
                ('team_id', models.CharField(db_column='team_id', max_length=3)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('home_games', models.IntegerField(blank=True, db_column='home_games', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('at_bats', models.IntegerField(blank=True, db_column='at_bats', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('cs', models.IntegerField(blank=True, db_column='CS', null=True)),
                ('ra', models.IntegerField(blank=True, db_column='RA', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
    ]
