# Generated by Django 3.1.7 on 2021-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0004_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=80)),
                ('team_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'BaseballTeams',
            },
        ),
    ]
