# Generated by Django 3.1.7 on 2021-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0005_add_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('player_number', models.IntegerField(null=True)),
                ('player_position', models.CharField(default='Player Position', max_length=4, null=True)),
            ],
            options={
                'db_table': 'Players',
            },
        ),
    ]
