# Generated by Django 3.1.7 on 2021-03-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0006_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballplayer',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='league_id',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='year_id',
        ),
        migrations.RemoveField(
            model_name='pitching',
            name='league_id',
        ),
        migrations.RemoveField(
            model_name='pitching',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='pitching',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='pitching',
            name='year_id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='league_id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='year_id',
        ),
        migrations.AddField(
            model_name='ballplayer',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batting',
            name='league',
            field=models.CharField(blank=True, db_column='league', default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='batting',
            name='player_name',
            field=models.CharField(blank=True, db_column='player_name', default=None, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='batting',
            name='team_name',
            field=models.CharField(blank=True, db_column='team_name', default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='batting',
            name='year',
            field=models.SmallIntegerField(blank=True, db_column='year_id', default=None, null=True),
        ),
        migrations.AddField(
            model_name='pitching',
            name='league',
            field=models.CharField(blank=True, db_column='league', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pitching',
            name='player_name',
            field=models.CharField(blank=True, db_column='player_name', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pitching',
            name='team_name',
            field=models.CharField(blank=True, db_column='team_name', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pitching',
            name='year',
            field=models.IntegerField(blank=True, db_column='year', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.CharField(blank=True, db_column='league', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_name',
            field=models.CharField(blank=True, db_column='team_name', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='year',
            field=models.IntegerField(db_column='year', default=None),
            preserve_default=False,
        ),
    ]
