# Generated by Django 3.1.7 on 2021-03-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0010_delete_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('league', models.CharField(blank=True, db_column='league', max_length=2, null=True)),
                ('team_name', models.CharField(blank=True, db_column='team_name', max_length=80, null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('home_games', models.IntegerField(blank=True, db_column='home_games', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('at_bats', models.IntegerField(blank=True, db_column='at_bats', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('cs', models.IntegerField(blank=True, db_column='CS', null=True)),
                ('ra', models.IntegerField(blank=True, db_column='RA', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
            ],
            options={
                'db_table': 'Team Data',
            },
        ),
    ]
