# Generated by Django 3.1.7 on 2021-03-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0011_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='league',
            field=models.CharField(blank=True, db_column='league', max_length=80, null=True),
        ),
    ]
