# Generated by Django 3.1.7 on 2021-03-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0012_auto_20210330_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='year',
            field=models.CharField(blank=True, db_column='year', max_length=80, null=True),
        ),
    ]
