# Generated by Django 3.1.7 on 2021-03-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0017_teams_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='year',
        ),
    ]
