# Generated by Django 3.1.7 on 2021-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0018_remove_teams_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_name',
        ),
        migrations.AddField(
            model_name='teams',
            name='team',
            field=models.CharField(blank=True, db_column='team', max_length=80, null=True),
        ),
    ]
