# Generated by Django 3.1.7 on 2021-03-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0019_auto_20210330_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='team_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
