# Generated by Django 3.1.7 on 2021-03-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0021_remove_pitching_stint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitching',
            name='year',
        ),
    ]
