# Generated by Django 3.1.7 on 2021-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0022_remove_pitching_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitching',
            name='league',
            field=models.CharField(blank=True, db_column='league', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='player_name',
            field=models.CharField(blank=True, db_column='player_name', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='team_name',
            field=models.CharField(blank=True, db_column='team_name', max_length=80, null=True),
        ),
    ]
