# Generated by Django 3.1.7 on 2021-03-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0023_auto_20210330_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballplayer',
            old_name='player_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='ballplayer',
            old_name='player_pos',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='ballplayer',
            name='height',
            field=models.FloatField(blank=True, db_column='height', null=True),
        ),
    ]
