# Generated by Django 3.1.7 on 2021-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0025_auto_20210331_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='league',
            field=models.CharField(blank=True, db_column='league', default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='player_name',
            field=models.CharField(blank=True, db_column='player_name', default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='team_name',
            field=models.CharField(blank=True, db_column='team_name', default=None, max_length=80, null=True),
        ),
    ]
