# Generated by Django 3.1.7 on 2021-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballapp', '0026_auto_20210331_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='batting',
            name='avg',
            field=models.FloatField(blank=True, db_column='avg', null=True),
        ),
    ]
