# Generated by Django 3.1.7 on 2021-03-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallPlayer',
            fields=[
                ('player_id', models.CharField(db_column='player_id', max_length=255, primary_key=True, serialize=False)),
                ('birth_country', models.CharField(blank=True, db_column='birth_country', max_length=255, null=True)),
                ('birth_state', models.CharField(blank=True, db_column='birth_state', max_length=255, null=True)),
                ('birth_city', models.CharField(blank=True, db_column='birth_city', max_length=255, null=True)),
                ('name_first', models.CharField(blank=True, db_column='name_first', max_length=255, null=True)),
                ('name_last', models.CharField(blank=True, db_column='name_last', max_length=255, null=True)),
                ('weight', models.IntegerField(blank=True, db_column='weight', null=True)),
                ('height', models.IntegerField(blank=True, db_column='height', null=True)),
                ('bats', models.CharField(blank=True, db_column='bats', max_length=255, null=True)),
                ('throws', models.CharField(blank=True, db_column='throws', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, db_column='player_id', max_length=9, null=True)),
                ('year_id', models.SmallIntegerField(blank=True, db_column='year_id', null=True)),
                ('stint', models.SmallIntegerField(blank=True, db_column='stint', null=True)),
                ('team_id', models.CharField(blank=True, db_column='team_id', max_length=3, null=True)),
                ('league_id', models.CharField(blank=True, db_column='league_id', max_length=2, null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('at_bats', models.IntegerField(blank=True, db_column='at_bats', null=True)),
                ('runs', models.IntegerField(blank=True, db_column='runs', null=True)),
                ('hits', models.IntegerField(blank=True, db_column='hits', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('cs', models.IntegerField(blank=True, db_column='CS', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('ibb', models.IntegerField(blank=True, db_column='IBB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('sh', models.IntegerField(blank=True, db_column='SH', null=True)),
                ('sf', models.IntegerField(blank=True, db_column='SF', null=True)),
                ('gidp', models.IntegerField(blank=True, db_column='GIDP', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, db_column='player_id', max_length=9, null=True)),
                ('year_id', models.IntegerField(blank=True, db_column='year_id', null=True)),
                ('stint', models.IntegerField(blank=True, db_column='stint', null=True)),
                ('team_id', models.CharField(blank=True, db_column='team_id', max_length=3, null=True)),
                ('league_id', models.CharField(blank=True, db_column='league_id', max_length=2, null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('gs', models.IntegerField(blank=True, db_column='GS', null=True)),
                ('shutouts', models.IntegerField(blank=True, db_column='shutouts', null=True)),
                ('saves', models.IntegerField(blank=True, db_column='saves', null=True)),
                ('outs_pitched', models.IntegerField(blank=True, db_column='outs_pitched', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('strikeouts', models.IntegerField(blank=True, db_column='strikeouts', null=True)),
                ('baopp', models.FloatField(blank=True, db_column='BAOpp', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
                ('ibb', models.IntegerField(blank=True, db_column='IBB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('bk', models.IntegerField(blank=True, db_column='BK', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('year_id', models.IntegerField(db_column='year_id', primary_key=True, serialize=False)),
                ('league_id', models.CharField(blank=True, db_column='league_id', max_length=2, null=True)),
                ('team_id', models.CharField(db_column='team_id', max_length=3)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('home_games', models.IntegerField(blank=True, db_column='home_games', null=True)),
                ('w', models.IntegerField(blank=True, db_column='W', null=True)),
                ('l', models.IntegerField(blank=True, db_column='L', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('at_bats', models.IntegerField(blank=True, db_column='at_bats', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('number_2b', models.IntegerField(blank=True, db_column='2B', null=True)),
                ('number_3b', models.IntegerField(blank=True, db_column='3B', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('sb', models.IntegerField(blank=True, db_column='SB', null=True)),
                ('cs', models.IntegerField(blank=True, db_column='CS', null=True)),
                ('ra', models.IntegerField(blank=True, db_column='RA', null=True)),
                ('era', models.FloatField(blank=True, db_column='ERA', null=True)),
            ],
        ),
    ]
