# Generated by Django 3.1.7 on 2021-03-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbaseball', '0002_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='ballplayer',
            name='player_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ballplayer',
            name='player_position',
            field=models.CharField(default='Player Position', max_length=4, null=True),
        ),
    ]
