# Generated by Django 3.1.7 on 2021-03-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbaseball', '0003_auto_20210328_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballplayer',
            name='player_position',
        ),
        migrations.AddField(
            model_name='ballplayer',
            name='player_pos',
            field=models.CharField(default='Player Position', max_length=80, null=True),
        ),
    ]
