# Generated by Django 3.1.7 on 2021-03-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allbaseball', '0004_auto_20210328_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BallPlayer',
        ),
        migrations.DeleteModel(
            name='Batting',
        ),
        migrations.DeleteModel(
            name='Pitching',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
